FROM node:22-alpine

WORKDIR /app

COPY frontend/package.json frontend/package-lock.json ./

RUN npm install

COPY frontend .

RUN npm run build

CMD ["npm", "run", "preview", "--", "--host", "0.0.0.0"]
