"""add_lenders_users_and_tenant_fks

Revision ID: 75dce44e8bc8
Revises: 0001_baseline_existing_schema
Create Date: 2026-08-01 14:51:11.506573

Autogenerated, then manually trimmed for production safety.

What this migration does:
1. Creates ``lenders`` / ``users`` only if they do not already exist
2. Adds nullable ``lender_id`` to ``clients`` and ``client_applications``
3. Adds indexes + foreign keys for those columns

Intentionally omitted from the raw autogenerate output (unsafe / unrelated):
- index renames on breaches / client_financials / client_applications
- NOT NULL / type alterations on existing columns
- dropping ``fk_financials_client`` / ``fk_positions_client``

``lender_id`` is nullable so existing rows remain valid until backfilled.
Do NOT run this migration until you have reviewed it.
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "75dce44e8bc8"
down_revision: Union[str, None] = "0001_baseline_existing_schema"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _table_names() -> set[str]:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    return set(inspector.get_table_names())


def _column_names(table_name: str) -> set[str]:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    return {column["name"] for column in inspector.get_columns(table_name)}


def upgrade() -> None:
    tables = _table_names()

    if "lenders" not in tables:
        op.create_table(
            "lenders",
            sa.Column("id", sa.Integer(), primary_key=True),
            sa.Column("name", sa.String(length=255), nullable=False),
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            ),
        )
        op.create_index(op.f("ix_lenders_id"), "lenders", ["id"], unique=False)
        op.create_index(op.f("ix_lenders_name"), "lenders", ["name"], unique=False)

    if "users" not in tables:
        op.create_table(
            "users",
            sa.Column("id", sa.Integer(), primary_key=True),
            sa.Column("email", sa.String(length=255), nullable=False),
            sa.Column("password_hash", sa.String(length=255), nullable=False),
            sa.Column("role", sa.String(length=50), nullable=False),
            sa.Column("lender_id", sa.Integer(), nullable=False),
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            ),
            sa.ForeignKeyConstraint(
                ["lender_id"],
                ["lenders.id"],
                name="fk_users_lender_id_lenders",
            ),
            sa.UniqueConstraint("email"),
        )
        op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
        op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
        op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
        op.create_index(op.f("ix_users_lender_id"), "users", ["lender_id"], unique=False)

    if "lender_id" not in _column_names("clients"):
        op.add_column(
            "clients",
            sa.Column("lender_id", sa.Integer(), nullable=True),
        )
        op.create_index(
            op.f("ix_clients_lender_id"),
            "clients",
            ["lender_id"],
            unique=False,
        )
        op.create_foreign_key(
            "fk_clients_lender_id_lenders",
            "clients",
            "lenders",
            ["lender_id"],
            ["id"],
        )

    if "lender_id" not in _column_names("client_applications"):
        op.add_column(
            "client_applications",
            sa.Column("lender_id", sa.Integer(), nullable=True),
        )
        op.create_index(
            op.f("ix_client_applications_lender_id"),
            "client_applications",
            ["lender_id"],
            unique=False,
        )
        op.create_foreign_key(
            "fk_client_applications_lender_id_lenders",
            "client_applications",
            "lenders",
            ["lender_id"],
            ["id"],
        )


def downgrade() -> None:
    tables = _table_names()

    if "client_applications" in tables and "lender_id" in _column_names(
        "client_applications"
    ):
        op.drop_constraint(
            "fk_client_applications_lender_id_lenders",
            "client_applications",
            type_="foreignkey",
        )
        op.drop_index(
            op.f("ix_client_applications_lender_id"),
            table_name="client_applications",
        )
        op.drop_column("client_applications", "lender_id")

    if "clients" in tables and "lender_id" in _column_names("clients"):
        op.drop_constraint(
            "fk_clients_lender_id_lenders",
            "clients",
            type_="foreignkey",
        )
        op.drop_index(op.f("ix_clients_lender_id"), table_name="clients")
        op.drop_column("clients", "lender_id")

    # Do not drop lenders/users on downgrade if they may contain production data.
    # Remove those tables only with an explicit, reviewed follow-up migration.
